apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Values.name }}
  port:
    targetPort: 8443-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
