name: composer-ai
# Default Namespace for the application components
application:
  defaultNamespace: composer-ai-app 

# Git Repository for the ArgoCD Application
repo:
  url: https://github.com/redhat-composer-ai/appOfApps.git # Change This on Fork
  branch: main

# Namespace for the ArgoCD Application
gitops:
  namespace: openshift-gitops

# Passing this value to all of the sub-applications to make it so we can dynamically figure out urls
clusterDomain: apps.cluster-c4gwj.c4gwj.sandbox1157.opentlc.com

# Default Values File for the Helm Chart
defaultValuesFile: values.yaml

# Applications to be deployed
applications:
  - name: vllm-model
    path: data-ingestion/vllm
  - name: weaviate
    path: data-ingestion/weaviate
  - name: kfp-pipeline
    path: data-ingestion/kfp
  - name: quarkus-llm-router
    path: chatbot/quarkus-llm-router
  - name: chatbot-ui
    path: chatbot/chatbot-ui
    # Add ignoreDifferences to allow deployment to be updated by ImageStream
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/spec/containers/0/image
  - name: mongodb
    path: chatbot/mongodb
  - name: bootstrap
    path: util/bootstrap
  - name: llm-guard
    path: chatbot/llm_guard
